making primer designer make sense
eastgenomics/primer_designer pull request #1
Opened 2021-03-24 22:33 UTC by jethror1

Many, many changes. Now is sensibly formatted, updated for python3 and with reasonably clean pep8 goodness.
All paths to tools / file paths moved to `config.py`, now easier to deploy on new servers.

All functions now split to 4 classes:
- Fusion(): fusion primer specific functions
- Sequence(): nucleotide seq. related functions, calls samtools, markup SNPs & repeats etc.
- Primer3(): functions for calling primer3 to design primers and handle output, does some formatting of primers
- Report(): functions to format sequence + some checks, does all the PDF formatting and writes out files

`bulk_design.py` still needs thought on modifying to call fusion primer designing

2021-03-24 22:33 UTC, pep8speaks commented
Hello @jethror1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`old_primer_designer_region.py`](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py):

> [Line 74:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L74): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (161 > 79 characters)
> [Line 96:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L96): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 97:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L97): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 100:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L100): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 101:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L101): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 194:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L194): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 220:44](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L220): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 220:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L220): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 234:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L234): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 79 characters)
> [Line 264:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L264): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 79 characters)
> [Line 352:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L352): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 370:29](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L370): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 370:77](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L370): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 370:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L370): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 79 characters)
> [Line 410:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L410): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 421:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L421): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)
> [Line 467:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L467): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (116 > 79 characters)
> [Line 483:43](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L483): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 483:45](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L483): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 483:68](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L483): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 483:70](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L483): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 664:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L664): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 665:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L665): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 739:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L739): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 762:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L762): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 810:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L810): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 811:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L811): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 842:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L842): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 909:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L909): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 1000:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L1000): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 79 characters)
> [Line 1019:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L1019): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 1020:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L1020): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 1021:80](https://github.com/eastgenomics/primer_designer/blob/84621e82ad7929dcc23d7faff2eb5831ee3068b2/old_primer_designer_region.py#L1021): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 1030:80](https://github.com/eastgenomics/primer_designer/blob/8462 [...]

2021-03-25 11:21 UTC, Yu-jinKim requested changes
> Reviewed 13 of 15 files at r1, 1 of 4 files at r4, 4 of 5 files at r6, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/1)* status: all files reviewed, 21 unresolved discussions (waiting on @jethror1)

___
*[bulk_design.py, line 37 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcmnhA9M-cWCCazElS:-MWcmnhA9M-cWCCazElT:bl5ut2g) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/bulk_design.py#L37)):*
> ```Python
> if __name__ == '__main__':
> 
>     if len(sys.argv) == 1:
> ```

no argparse?
___
*[bulk_design.py, line 60 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcnEnt-7TGxo89DEj7:-MWcnEnt-7TGxo89DEj8:b4az70w) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/bulk_design.py#L60)):*
> ```Python
> 
>     primer_designer_path = \
>         f"{Path(__file__).parent.absolute()}/primer_designer_region.py"
> ```

this makes me feel like the git could be structure like a python package. Maybe for later
___
*[bulk_design.py, line 75 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWco1y28UPI_22lUFvL:-MWco1y28UPI_22lUFvM:b-vyk3ry) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/bulk_design.py#L75)):*
> ```Python
> 
>             cmd = (
>                 f"{primer_designer_path} -c {chrom} -p {npos} -o {testname} "
> ```

yeah needs to be made into a python package later, feels weird calling a python script in another python script
___
*[bulk_design.py, line 89 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcntfA-cKVTgfWgby4:-MWcntfA-cKVTgfWgby5:bf4puo0) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/bulk_design.py#L89)):*
> ```Python
> 
>     os.chdir("..")
>     subprocess.check_call("zip -j {} {}/*pdf".format(outfile, working_dir))
> ```

basic zip module exists in Python just FYI, might be cleaner to do a full Python thing in the future
___
*[primer_designer_region.py, line 27 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcoMY_DCRy_ddVT_Gv:-MWcoMY_DCRy_ddVT_Gw:b-okt4bk) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L27)):*
> ```Python
> 
> # paths to req. tools, defined in config
> from config import SAMTOOLS, TABIX, SMALT, PRIMER3, THERMO_PARAMS, FONT, \
> ```

config file is called example_config.py, does that work?
___
*[primer_designer_region.py, line 100 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcpUhl3E-tRqO2foel:-MWcpUhl3E-tRqO2foem:b-slnopv) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L100)):*
> ```Python
> 
>         Args:
>             - coord_dicts (dict): nested dict of coordinate dicts
> ```

not same name as variable
___
*[primer_designer_region.py, line 102 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcpaqeD8JYyLM3afB4:-MWcpaqeD8JYyLM3afB5:b7fs85t) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L102)):*
> ```Python
>             - coord_dicts (dict): nested dict of coordinate dicts
>         Returns:
>             - coord_dicts (dict): nested dict of coordinate dicts
> ```

what about coord2seq_dict for added verbosity
___
*[primer_designer_region.py, line 118 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcpKan-4Vj7-jNcdXa:-MWcpKan-4Vj7-jNcdXb:bv0doym) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L118)):*
> ```Python
>                     f"signs to be used: <>. The sign used:  {dict['SIDE']}"
>                 ))
>                 break
> ```

doesn't that warrant an exception raising? does the code continue to work if it goes here?
___
*[primer_designer_region.py, line 128 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcpydF9Azqk8OYw0tQ:-MWcpydF9Azqk8OYw0tR:bm3xmd1) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L128)):*
> ```Python
> 
>         Args:
>             -
> ```

empty sadness
___
*[primer_designer_region.py, line 137 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcqFSEEkRKi2HCjo6Q:-MWcqFSEEkRKi2HCjo6R:btiolut) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L137)):*
> ```Python
>         }
> 
>         # DARK_SIDE is requrired to store original SIDE value, which is
> ```

typo + needed star wars reference
___
*[primer_designer_region.py, line 176 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcqwRC0XZbA9m42Ldo:-MWcqwRC0XZbA9m42Ldp:b-2aa6xq) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L176)):*
> ```Python
> 
>         else:
>             print("This fusion is not possible")
> ```

a bit more info as to why it's not possible would be useful
___
*[primer_designer_region.py, line 232 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcrVqQ-Ey54UJmzNKp:-MWcrVqQ-Ey54UJmzNKq:b8yb6p9) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L232)):*
> ```Python
> 
>         Args:
>             - flank (int):
> ```

missing info
___
*[primer_designer_region.py, line 233 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcraBd2QWL6hL17-BL:-MWcraBd2QWL6hL17-BM:b-b0ui24) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L233)):*
> ```Python
>         Args:
>             - flank (int):
>             - sequence (list): list of nucleotide sequences (?)
> ```

(?) ? you not sure it's for? + it looks like it's a dict looking at the code below
___
*[primer_designer_region.py, line 244 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcsI0a0CPzstXUtWcL:-MWcsI0a0CPzstXUtWcM:b-8i8n5f) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L244)):*
> ```Python
>         """
>         if FUSION:
>             for key, value in sequence.items():
> ```

i don't understand this loop. I'm guessing it's legacy code but key and value are not used so why even loop through them? I'm confused
___
*[primer_designer_region.py, line 250 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcsfy10cKOOerzMCln:-MWcsfy10cKOOerzMClo:b-l915i0) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L250)):*
> ```Python
>                 side = sequence['SIDE']
> 
>                 if side == "<":
> ```

like this is not going to be different from one iteration to the next since `side = sequence['SIDE']` at every loop
___
*[primer_designer_region.py, line 332 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcuMqQ1dSM5QoUwwid:-MWcuMqQ1dSM5QoUwwie:b3uueul) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L332)):*
> ```Python
> 
>         Args:
>             - tags (list): empty list to add tags to (?)
> ```

missing sequence param
___
*[primer_designer_region.py, line 365 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcud4SChAJolBY_nCv:-MWcud4SChAJolBY_nCw:bwikqsu) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd42 [...]

2021-03-25 11:43 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/1)* status: all files reviewed, 21 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[bulk_design.py, line 37 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcmnhA9M-cWCCazElS:-MWdA1DK-hdLeY0u_8lL:b-gsgb0q) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/bulk_design.py#L37)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

no argparse?
</blockquote></details>

can / should be replaced, to do
___
*[bulk_design.py, line 60 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcnEnt-7TGxo89DEj7:-MWdA3mo4qi0iUc1O2JA:b-3lbu8u) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/bulk_design.py#L60)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

this makes me feel like the git could be structure like a python package. Maybe for later
</blockquote></details>

yep definitely, this whole script needs more thought as it will be used to be called by Ark
___
*[bulk_design.py, line 75 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWco1y28UPI_22lUFvL:-MWdAAlq0UznHMLC6oUQ:bnj7hl0) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/bulk_design.py#L75)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

yeah needs to be made into a python package later, feels weird calling a python script in another python script
</blockquote></details>

same as above
___
*[bulk_design.py, line 89 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcntfA-cKVTgfWgby4:-MWdACdV8b4uaKQXQX9U:b-mhcf5a) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/bulk_design.py#L89)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

basic zip module exists in Python just FYI, might be cleaner to do a full Python thing in the future
</blockquote></details>

indeed, to do
___
*[primer_designer_region.py, line 27 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcoMY_DCRy_ddVT_Gv:-MWdAJUf0TAnBBUHg8wC:b-lj5zek) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L27)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

config file is called example_config.py, does that work?
</blockquote></details>

that is just an empty example file so everything to import is there, real one is called `config.py`, is in readme
___
*[primer_designer_region.py, line 102 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcpaqeD8JYyLM3afB4:-MWdAXXz4RJ7J7z7Ktr3:b1ngav3) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L102)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

what about coord2seq_dict for added verbosity
</blockquote></details>

will do, not changed much since of var names yet as there's lots but its to do
___
*[primer_designer_region.py, line 118 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcpKan-4Vj7-jNcdXa:-MWdAdy48oNzKJJAZeYV:b-b2h6ma) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L118)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

doesn't that warrant an exception raising? does the code continue to work if it goes here?
</blockquote></details>

probably, good idea
___
*[primer_designer_region.py, line 128 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcpydF9Azqk8OYw0tQ:-MWdAh2Q4_Rt7ZIZrMY5:b-54hi7g) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L128)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

empty sadness
</blockquote></details>

yeah I got lazy since there was lots
___
*[primer_designer_region.py, line 176 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcqwRC0XZbA9m42Ldo:-MWdAp-BEHoeo0aulotn:b-e6jxs1) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L176)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

a bit more info as to why it's not possible would be useful
</blockquote></details>

question for Nikita, also probs better with an assertion instead of sys.exit() to catch it when run via Ark
___
*[primer_designer_region.py, line 232 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcrVqQ-Ey54UJmzNKp:-MWdAzC0-4HMQcYVrJHt:bf7s534) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L232)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

missing info
</blockquote></details>

laziness
___
*[primer_designer_region.py, line 233 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcraBd2QWL6hL17-BL:-MWdB3Wx4UkwseGJoSdH:bdi394) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L233)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

(?) ? you not sure it's for? + it looks like it's a dict looking at the code below
</blockquote></details>

yeah I added ? where I wasn't 100%, will change
___
*[primer_designer_region.py, line 244 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcsI0a0CPzstXUtWcL:-MWdB7t80_QC9gInVfwq:b-u6um4z) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L244)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i don't understand this loop. I'm guessing it's legacy code but key and value are not used so why even loop through them? I'm confused
</blockquote></details>

looks to loop in main and pass single dict here for fusion, so yeah its pointless
___
*[primer_designer_region.py, line 365 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcud4SChAJolBY_nCv:-MWdBLZp0FyNaR0zk2qN:b7f0k6c) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L365)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

> ```
> 
>             - startpos (int):
>             - endpos (int):
>             - FUSION (bool):
> ```
missing docstrings
</blockquote></details>

l a z i n e s s
___
*[primer_designer_region.py, line 661 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWd0bkg1epWWFXTlcY9:-MWdBQZx6qw40E8j0J-Q:b-e9wm78) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L661)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

might be useful to do something with it if it exists
</blockquote></details>

indeed, I added this in, will check for out vs err and handle appropriately


<!-- Sent from Reviewable.io -->

2021-03-25 12:32 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/1)* status: 18 of 19 files reviewed, 21 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[primer_designer_region.py, line 118 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcpKan-4Vj7-jNcdXa:-MWdIYqu6kRxz4wjusim:b-896fix) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L118)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

probably, good idea
</blockquote></details>

Done.
___
*[primer_designer_region.py, line 128 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcpydF9Azqk8OYw0tQ:-MWdI_z85qe1wncnhwtA:b-896fix) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L128)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

yeah I got lazy since there was lots
</blockquote></details>

Done.
___
*[primer_designer_region.py, line 137 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcqFSEEkRKi2HCjo6Q:-MWdIa_w8Va9rQls5tVc:b-896fix) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L137)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

typo + needed star wars reference
</blockquote></details>

Done.
___
*[primer_designer_region.py, line 176 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcqwRC0XZbA9m42Ldo:-MWdIcn34caqwZCI-P6J:b-896fix) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L176)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

question for Nikita, also probs better with an assertion instead of sys.exit() to catch it when run via Ark
</blockquote></details>

Done.
___
*[primer_designer_region.py, line 332 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcuMqQ1dSM5QoUwwid:-MWdKta32F1olrrpOwAd:b-896fix) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L332)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

missing sequence param
</blockquote></details>

Done.
___
*[primer_designer_region.py, line 661 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWd0bkg1epWWFXTlcY9:-MWdMh8CCqeyTkfQPp8v:b-896fix) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L661)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

indeed, I added this in, will check for out vs err and handle appropriately
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-16 15:43 UTC, JasonLing95 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/1)* status: 13 of 28 files reviewed, 24 unresolved discussions (waiting on @JasonLing95, @jethror1, and @Yu-jinKim)

___
*[Dockerfile, line 12 at r12](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-Mw1CY8f5GnKKnMAThiE:-Mw1CY8f5GnKKnMAThiF:b7ljorf) ([raw file](https://github.com/eastgenomics/primer_designer/blob/582e0c49e5f3cbd186deeed43fa49be33c08fab0/Dockerfile#L12)):*
> ```Dockerfile
> RUN cd htslib-1.5 && ./configure --prefix=/home/software/htslib && make && make install
> 
> # get samtools and build
> ```

samtools has been updated to samtools-1.14 (https://github.com/samtools/samtools/releases)



_Code quote:_
```Dockerfile
# get samtools and build
```
___
*[Dockerfile, line 22 at r12](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-Mw1GKRV0VvobTWiQua7:-Mw1GKRV0VvobTWiQua8:bydclsq) ([raw file](https://github.com/eastgenomics/primer_designer/blob/582e0c49e5f3cbd186deeed43fa49be33c08fab0/Dockerfile#L22)):*
> ```Dockerfile
> RUN cd software/smalt-0.7.6 && ./configure && make && make install
> 
> # get and build primer3
> ```

primer3 has been updated to 2.6.1 (https://github.com/primer3-org/primer3/releases)



_Code quote:_
```Dockerfile
# get and build primer3
```
___
*[bin/primer_designer_region.py, line 914 at r12](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-Mw29wPw1kklCUT4_xWH:-Mw29wPw1kklCUT4_xWI:bwbloie) ([raw file](https://github.com/eastgenomics/primer_designer/blob/582e0c49e5f3cbd186deeed43fa49be33c08fab0/bin/primer_designer_region.py#L914)):*
> ```Python
>             seq_dict = self.primer_report(chromo, startpos, endpos, seq_dict)
> 
>         return seq_dict
> ```

the seq_dict even if empty will still continue the process of producing an empty PDF. Most likely event is smalt map crashing which produce empty result in smalt_out. Probably need an error handling either in this function or after this function to check passed_primer to return error if empty



_Code quote:_
```Python
seq_dict
```


<!-- Sent from Reviewable.io -->

2022-02-16 16:27 UTC, JasonLing95 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/1)* status: 13 of 28 files reviewed, 26 unresolved discussions (waiting on @JasonLing95, @jethror1, and @Yu-jinKim)

___
*[README.md, line 28 at r12](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-Mw2DMej9ny0UBsU3Ll6:-Mw2DMekEDghIjKopxLA:b-d0kdle) ([raw file](https://github.com/eastgenomics/primer_designer/blob/582e0c49e5f3cbd186deeed43fa49be33c08fab0/README.md#L28)):*
> ```Markdown
> - Docker (optional)
> 
> n.b. index files for reference genome and dbSNP vcf need generating with both `samtools faidx` and `smalt index INDEX REFSEQ-FILE`
> ```

Worth mentioning that samtools faidx is included as part of the script so user only need the FASTA file as reference input and the FAI will be generated automatically.
Meanwhile, the user will need to index the FASTA manually using smalt index -k 11 -s2 <output name> <reference_file> and put it in the reference_files folder



_Code quote:_
```Markdown
 index files for reference genome and dbSNP vcf need generating with both `samtools faidx` and `smalt index INDEX REFSEQ-FILE`
```
___
*[README.md, line 91 at r12](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-Mw2EBwQ9jMDyFhC24dj:-Mw2EBwQ9jMDyFhC24dk:bgy2y6d) ([raw file](https://github.com/eastgenomics/primer_designer/blob/582e0c49e5f3cbd186deeed43fa49be33c08fab0/README.md#L91)):*
> ```Markdown
> <br></br>
> 
> Primer designer may also be called via the `bulk_design.py` script, this allows for passing a `.txt` file of multiple regions at once and outputs a `.zip` file of designer primer reports.
> ```

I can't seem to find the bulk_design.py in this branch



_Code quote:_
```Markdown
bulk_design.py`
```


<!-- Sent from Reviewable.io -->

2022-02-16 21:31 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/1)* status: 13 of 28 files reviewed, 26 unresolved discussions (waiting on @JasonLing95, @jethror1, and @Yu-jinKim)

___
*[Dockerfile, line 12 at r12](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-Mw1CY8f5GnKKnMAThiE:-Mw3QicoEt_0CQVP0Puo:b2vht7i) ([raw file](https://github.com/eastgenomics/primer_designer/blob/582e0c49e5f3cbd186deeed43fa49be33c08fab0/Dockerfile#L12)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

samtools has been updated to samtools-1.14 (https://github.com/samtools/samtools/releases)
</blockquote></details>

samtools is a sensible thing to upgrade, will change this
___
*[Dockerfile, line 22 at r12](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-Mw1GKRV0VvobTWiQua7:-Mw3R00s2Xon12UZhNmH:b1sgbmo) ([raw file](https://github.com/eastgenomics/primer_designer/blob/582e0c49e5f3cbd186deeed43fa49be33c08fab0/Dockerfile#L22)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

primer3 has been updated to 2.6.1 (https://github.com/primer3-org/primer3/releases)
</blockquote></details>

will need to review change logs for this one
___
*[README.md, line 91 at r12](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-Mw2EBwQ9jMDyFhC24dj:-Mw3R6kL9bXWGQdSbBAE:b-kymbyn) ([raw file](https://github.com/eastgenomics/primer_designer/blob/582e0c49e5f3cbd186deeed43fa49be33c08fab0/README.md#L91)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

I can't seem to find the bulk_design.py in this branch
</blockquote></details>

yeah I scrapped it, it was used by Ark to call primer designer but I rewrote the calling in Ark to be better and not need it, will remove it from here
___
*[bin/primer_designer_region.py, line 914 at r12](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-Mw29wPw1kklCUT4_xWH:-Mw3RRk44lZGJp9iIWps:bo1r9dl) ([raw file](https://github.com/eastgenomics/primer_designer/blob/582e0c49e5f3cbd186deeed43fa49be33c08fab0/bin/primer_designer_region.py#L914)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

the seq_dict even if empty will still continue the process of producing an empty PDF. Most likely event is smalt map crashing which produce empty result in smalt_out. Probably need an error handling either in this function or after this function to check passed_primer to return error if empty
</blockquote></details>

good catch, will handle this properly. Raising proper errors is good as these will be caught and displayed/logged by Django in Ark


<!-- Sent from Reviewable.io -->

2022-04-20 09:27 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/1)* status: 13 of 28 files reviewed, 26 unresolved discussions (waiting on @JasonLing95, @jethror1, and @Yu-jinKim)

___
*[bulk_design.py, line 37 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcmnhA9M-cWCCazElS:-N0596hL3_-aethb4VER:b-thgqzi) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/bulk_design.py#L37)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can / should be replaced, to do
</blockquote></details>

deleted this script and moved the calling logic directly into new Ark
___
*[README.md, line 28 at r12](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-Mw2DMej9ny0UBsU3Ll6:-N05Aeq4CsSkOBoVfq8X:bc4idbl) ([raw file](https://github.com/eastgenomics/primer_designer/blob/582e0c49e5f3cbd186deeed43fa49be33c08fab0/README.md#L28)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

Worth mentioning that samtools faidx is included as part of the script so user only need the FASTA file as reference input and the FAI will be generated automatically.
Meanwhile, the user will need to index the FASTA manually using smalt index -k 11 -s2 <output name> <reference_file> and put it in the reference_files folder
</blockquote></details>

the .fai is the index of the FASTA generated by samtools faidx, the .sma and .smi are generated by smalt index
___
*[README.md, line 91 at r12](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-Mw2EBwQ9jMDyFhC24dj:-N05AFMHDUH6Kto2XcsY:b-gbcq2p) ([raw file](https://github.com/eastgenomics/primer_designer/blob/582e0c49e5f3cbd186deeed43fa49be33c08fab0/README.md#L91)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

yeah I scrapped it, it was used by Ark to call primer designer but I rewrote the calling in Ark to be better and not need it, will remove it from here
</blockquote></details>

removed from readme
___
*[primer_designer_region.py, line 100 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcpUhl3E-tRqO2foel:-N05B2Iu0mbyspYOjesa:b-896fix) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L100)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

not same name as variable
</blockquote></details>

Done.
___
*[primer_designer_region.py, line 102 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcpaqeD8JYyLM3afB4:-N05BAZ02fLXkjzv9dIz:b4dq71w) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L102)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

will do, not changed much since of var names yet as there's lots but its to do
</blockquote></details>

not gonna change it as it requires creating a new dict instead of just modifying the passed one and returning, its a short function with no other logic so don't think its needed. Have updated the docstring to say what is added when it is returned
___
*[primer_designer_region.py, line 232 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcrVqQ-Ey54UJmzNKp:-N05BZQ40Ut-lUj5LLcg:bb6un1j) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L232)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

laziness
</blockquote></details>

Done
___
*[primer_designer_region.py, line 244 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcsI0a0CPzstXUtWcL:-N05Boa146YgJ6oxfasn:bdq8ncd) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L244)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

looks to loop in main and pass single dict here for fusion, so yeah its pointless
</blockquote></details>

deleted it and added comment
___
*[primer_designer_region.py, line 250 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcsfy10cKOOerzMCln:-N05BuT5CeTdLiV1f-CI:bb6un1j) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L250)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

like this is not going to be different from one iteration to the next since `side = sequence['SIDE']` at every loop
</blockquote></details>

Done
___
*[primer_designer_region.py, line 365 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcud4SChAJolBY_nCv:-N05BvYgDy1Z9EMes1DT:bb6un1j) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L365)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

l a z i n e s s
</blockquote></details>

Done
___
*[primer_designer_region.py, line 429 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcyXdRAug0Tfi0tV8E:-N05C0MODwVSVJPmdc4F:b56hbik) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L429)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

not a list anymore
</blockquote></details>

docstring is type `str` returned for both
___
*[primer_designer_region.py, line 681 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWd17pF3cApps4L9q_r:-N05GqD8Bz-B84FWicy6:b-896fix) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L681)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

> ```
>             - seq_id (int):
>             - seq (str):
> ```
docstring
</blockquote></details>

Done.
___
*[primer_designer_region.py, line 715 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWd28wB5zSsik__YglR:-N05Gr3-0We0E-GmW-SO:b-896fix) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L715)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[bin/primer_designer_region.py, line 914 at r12](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-Mw29wPw1kklCUT4_xWH:-N05I2m3CRxtZgJ0ps1D:bb6un1j) ([raw file](https://github.com/eastgenomics/primer_designer/blob/582e0c49e5f3cbd186deeed43fa49be33c08fab0/bin/primer_designer_region.py#L914)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

good catch, will handle this properly. Raising proper errors is good as these will be caught and displayed/logged by Django in Ark
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-04-20 09:31 UTC, Yu-jinKim reviewed
> Reviewed 1 of 2 files at r7, 7 of 9 files at r10, 7 of 9 files at r12, 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/1)* status: all files reviewed, 6 unresolved discussions (waiting on @JasonLing95 and @jethror1)



<!-- Sent from Reviewable.io -->

2022-04-20 09:35 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/1)* status: all files reviewed, 6 unresolved discussions (waiting on @JasonLing95 and @Yu-jinKim)

___
*[primer_designer_region.py, line 102 at r7](https://reviewable.io/reviews/eastgenomics/primer_designer/1#-MWcpaqeD8JYyLM3afB4:-N05JnGRE-rtUKZaIDTY:b-896fix) ([raw file](https://github.com/eastgenomics/primer_designer/blob/aedd421c2553dbf0b2c052d10fb308e32dfa0cea/primer_designer_region.py#L102)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

not gonna change it as it requires creating a new dict instead of just modifying the passed one and returning, its a short function with no other logic so don't think its needed. Have updated the docstring to say what is added when it is returned
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-20 11:17 UTC, JasonLing95 approved these changes
> Reviewed 13 of 15 files at r1, 4 of 9 files at r10, 7 of 9 files at r12, 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/1)* status: all files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2022-04-20 11:21 UTC, merged