Added directory argument
eastgenomics/primer_designer pull request #4
Opened 2022-07-18 20:54 UTC by JasonLing95

# Changes
- directory argument `-d` - If specified, primer pdfs will be generated in `/output/<specified directory name>` rather than `/output`

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/primer_designer/4)

2022-07-18 20:54 UTC, pep8speaks commented
Hello @JasonLing95! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`bin/primer_designer_region.py`](https://github.com/eastgenomics/primer_designer/blob/9fae4f6a8c428c0804041f02c9b5546d979fe139/bin/primer_designer_region.py):

> [Line 1938:1](https://github.com/eastgenomics/primer_designer/blob/9fae4f6a8c428c0804041f02c9b5546d979fe139/bin/primer_designer_region.py#L1938): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2022-07-18 21:03 UTC, jethror1 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JasonLing95 and @jethror1)

___
*[`bin/primer_designer_region.py` line 1940 at r1](https://reviewable.io/reviews/eastgenomics/primer_designer/4#-N7I5YmT8TiwcgEPzw9r:-N7I5YmUEqm5NZN7GxbP:bxqgdco) ([raw file](https://github.com/eastgenomics/primer_designer/blob/9fae4f6a8c428c0804041f02c9b5546d979fe139/bin/primer_designer_region.py#L1940)):*
> ```Python
>     
>     if args.directory:
>         output_dir = f'{parent_dir}/output/{args.directory}/'
> ```

this seems odd, if I provided an output directory as an argument, I'd expect it not to be relative to another directory other than current (i.e. if someone provided `-d ../some_dir`, I'd expect it to be in a directory named `some_dir` in the same as the parent, this would add it to `/output/../some_dir` -> `./some_dir`. 

Maybe something like [this](https://stackoverflow.com/a/3320429) to get if its absolute, if not resolve it relative to parent (`os.path.join(os.getcwd(), args.directory)`) ?


<!-- Sent from Reviewable.io -->

2022-07-18 23:06 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`bin/primer_designer_region.py` line 1940 at r1](https://reviewable.io/reviews/eastgenomics/primer_designer/4#-N7I5YmT8TiwcgEPzw9r:-N7IMUyNEGTg-VrN0QGt:b-o8wiz8) ([raw file](https://github.com/eastgenomics/primer_designer/blob/9fae4f6a8c428c0804041f02c9b5546d979fe139/bin/primer_designer_region.py#L1940)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this seems odd, if I provided an output directory as an argument, I'd expect it not to be relative to another directory other than current (i.e. if someone provided `-d ../some_dir`, I'd expect it to be in a directory named `some_dir` in the same as the parent, this would add it to `/output/../some_dir` -> `./some_dir`. 

Maybe something like [this](https://stackoverflow.com/a/3320429) to get if its absolute, if not resolve it relative to parent (`os.path.join(os.getcwd(), args.directory)`) ?
</blockquote></details>

the `-d` will mostly be used by Genetic Ark as we assign each query a random filename string to create folder


<!-- Sent from Reviewable.io -->

2022-07-19 07:17 UTC, jethror1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/4#-:-N7KJNjs-lqnyjVFUrUL:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-07-19 07:17 UTC, merged